const products = [
  {
    id: 1,
    company: 'Tiffany & Co.',
    productName: 'Gold Necklace',
    style: 'Classic',
    weight: '15g',
    color: 'Gold',
    material: '14k Gold',
    shortDescription: 'Elegant gold necklace made of 14k Gold',
    price: 49.99,
    src: '/assets/jewellery.jpeg',
    additionalImages: [
      '/assets/jewellery.jpeg',
      '/assets/jewellery2.jpeg',
      '/assets/jewellery3.jpeg',
      '/assets/jewellery4.jpeg',
      '/assets/jewellery5.jpeg',
      '/assets/jewellery6.jpeg',
      '/assets/jewellery7.jpeg',
      '/assets/jewellery8.jpeg',
    ],
  },
  {
    id: 2,
    company: 'Cartier',
    productName: 'Silver Bracelet',
    style: 'Vintage',
    weight: '10g',
    color: 'Silver',
    material: 'Sterling Silver',
    shortDescription: 'Beautiful silver bracelet made of Sterling Silver',
    price: 29.99,
    src: '/assets/jewellery.jpeg',
    additionalImages: [
      '/assets/jewellery.jpeg',
      '/assets/jewellery2.jpeg',
      '/assets/jewellery3.jpeg',
      '/assets/jewellery4.jpeg',
      '/assets/jewellery5.jpeg',
      '/assets/jewellery6.jpeg',
      '/assets/jewellery7.jpeg',
      '/assets/jewellery8.jpeg',
    ],
  },
  {
    id: 3,
    company: 'Bulgari',
    productName: 'Rose Gold Ring',
    style: 'Modern',
    weight: '25g',
    color: 'Rose Gold',
    material: '18k Rose Gold',
    shortDescription: 'Stylish rose gold ring made of 18k Rose Gold',
    price: 69.99,
    src: '/assets/jewellery.jpeg',
    additionalImages: [
      '/assets/jewellery.jpeg',
      '/assets/jewellery2.jpeg',
      '/assets/jewellery3.jpeg',
      '/assets/jewellery4.jpeg',
      '/assets/jewellery5.jpeg',
      '/assets/jewellery6.jpeg',
      '/assets/jewellery7.jpeg',
      '/assets/jewellery8.jpeg',
    ],
  },
  {
    id: 4,
    company: 'Chopard',
    productName: 'Silver Earrings',
    style: 'Minimalist',
    weight: '5g',
    color: 'Silver',
    material: '925 Sterling Silver',
    shortDescription: 'Simple silver earrings made of 925 Sterling Silver',
    price: 39.99,
    src: '/assets/jewellery.jpeg',
    additionalImages: [
      '/assets/jewellery.jpeg',
      '/assets/jewellery2.jpeg',
      '/assets/jewellery3.jpeg',
      '/assets/jewellery4.jpeg',
      '/assets/jewellery5.jpeg',
      '/assets/jewellery6.jpeg',
      '/assets/jewellery7.jpeg',
      '/assets/jewellery8.jpeg',
    ],
  },
  {
    id: 5,
    company: 'Tiffany & Co.',
    productName: 'Bronze Necklace',
    style: 'Bohemian',
    weight: '20g',
    color: 'Bronze',
    material: 'Bronze',
    shortDescription: 'Boho-style bronze necklace made of Bronze',
    price: 19.99,
    src: '/assets/jewellery.jpeg',
    additionalImages: [
      '/assets/jewellery.jpeg',
      '/assets/jewellery2.jpeg',
      '/assets/jewellery3.jpeg',
      '/assets/jewellery4.jpeg',
      '/assets/jewellery5.jpeg',
      '/assets/jewellery6.jpeg',
      '/assets/jewellery7.jpeg',
      '/assets/jewellery8.jpeg',
    ],
  },
  {
    id: 6,
    company: 'Cartier',
    productName: 'Silver Pendant',
    style: 'Contemporary',
    weight: '12g',
    color: 'Silver',
    material: '925 Sterling Silver',
    shortDescription: 'Chic silver pendant made of 925 Sterling Silver',
    price: 59.99,
    src: '/assets/jewellery.jpeg',
    additionalImages: [
      '/assets/jewellery.jpeg',
      '/assets/jewellery2.jpeg',
      '/assets/jewellery3.jpeg',
      '/assets/jewellery4.jpeg',
      '/assets/jewellery5.jpeg',
      '/assets/jewellery6.jpeg',
      '/assets/jewellery7.jpeg',
      '/assets/jewellery8.jpeg',
    ],
  },
  {
    id: 7,
    company: 'Bulgari',
    productName: 'Rose Gold Bangle',
    style: 'Minimalist',
    weight: '8g',
    color: 'Rose Gold',
    material: '18k Rose Gold',
    shortDescription: 'Simple rose gold bangle made of 18k Rose Gold',
    price: 79.99,
    src: '/assets/jewellery.jpeg',
    additionalImages: [
      '/assets/jewellery.jpeg',
      '/assets/jewellery2.jpeg',
      '/assets/jewellery3.jpeg',
      '/assets/jewellery4.jpeg',
      '/assets/jewellery5.jpeg',
      '/assets/jewellery6.jpeg',
      '/assets/jewellery7.jpeg',
      '/assets/jewellery8.jpeg',
    ],
  },
  {
    id: 8,
    company: 'Chopard',
    productName: 'Silver Anklet',
    style: 'Modern',
    weight: '18g',
    color: 'Silver',
    material: '925 Sterling Silver',
    shortDescription: 'Trendy silver anklet made of 925 Sterling Silver',
    price: 89.99,
    src: '/assets/jewellery.jpeg',
    additionalImages: [
      '/assets/jewellery.jpeg',
      '/assets/jewellery2.jpeg',
      '/assets/jewellery3.jpeg',
      '/assets/jewellery4.jpeg',
      '/assets/jewellery5.jpeg',
      '/assets/jewellery6.jpeg',
      '/assets/jewellery7.jpeg',
      '/assets/jewellery8.jpeg',
    ],
  },
  {
    id: 9,
    company: 'Tiffany & Co.',
    productName: 'Gold Earrings',
    style: 'Vintage',
    weight: '22g',
    color: 'Gold',
    material: '22k Gold',
    shortDescription: 'Vintage-style gold earrings made of 22k Gold',
    price: 99.99,
    src: '/assets/jewellery.jpeg',
    additionalImages: [
      '/assets/jewellery.jpeg',
      '/assets/jewellery2.jpeg',
      '/assets/jewellery3.jpeg',
      '/assets/jewellery4.jpeg',
      '/assets/jewellery5.jpeg',
      '/assets/jewellery6.jpeg',
      '/assets/jewellery7.jpeg',
      '/assets/jewellery8.jpeg',
    ],
  },
  {
    id: 10,
    company: 'Cartier',
    productName: 'Bronze Bracelet',
    style: 'Bohemian',
    weight: '14g',
    color: 'Bronze',
    material: 'Bronze',
    shortDescription: 'Boho-style bronze bracelet made of Bronze',
    price: 49.99,
    src: '/assets/jewellery.jpeg',
    additionalImages: [
      '/assets/jewellery.jpeg',
      '/assets/jewellery2.jpeg',
      '/assets/jewellery3.jpeg',
      '/assets/jewellery4.jpeg',
      '/assets/jewellery5.jpeg',
      '/assets/jewellery6.jpeg',
      '/assets/jewellery7.jpeg',
      '/assets/jewellery8.jpeg',
    ],
  },
];

export default products;
